### ISSUE TITLE
Game license

### ISSUE THREAD

**Issue by tinco** [jawslouis/Influence-Game#1]
Hi! Your game is a lot of fun. I noticed in the package.json it says the game is licensed ISC, is that intentional? I think it's the default setting so I'd want to check before I play with the source code.

I made a little system for making simple games like this multiplayer for a hackathon recently, and I was thinking of trying to make yours multiplayer, but only if it's cool with you of course :)

**Comment by jawslouis** [comment]
Thanks for checking. Yes please go ahead and play with the source code. 
I'd love to play a multiplayer version of the game!

**Comment by jaredsilver** [comment]
Thanks for making this delightful game, @jawslouis! I would also love to play a multi-player version of it, @tinco! 🎉

**Comment by jawslouis** [comment]
Closed
